timeout: 1200s
steps:
# terraform init -input=false
- id: init_infrastructure
  name: gcr.io/$PROJECT_ID/terraform-cloudbuilder:latest
  dir: /workspace/terraform/
  args:
  - init
  - -input=false
# terraform validate
- id: validate_infrastructure
  name: gcr.io/$PROJECT_ID/terraform-cloudbuilder:latest
  dir: /workspace/terraform/
  args:
  - validate
# terraform plan -input=false -out=tfplan
- id: plan_infrastructure
  name: gcr.io/$PROJECT_ID/terraform-cloudbuilder:latest
  dir: /workspace/terraform/
  args:
  - plan
  - -input=false
  - -out=tfplan
  - -lock=false

# terraform apply -auto-approve -input=false tfplan
- id: apply_infrastructure
  name: gcr.io/$PROJECT_ID/terraform-cloudbuilder:latest
  dir: /workspace/terraform/
  args:
  - apply
  - -auto-approve
  - -input=false
  - -lock=false
  - tfplan
logsBucket: 'gs://my-bucket-terraform'
options:
  logging: GCS_ONLY
