timeout: 1200s
steps:
# terraform init -input=false
- id: init_infrastructure
  name: gcr.ip/$PROJECT_ID/terraform-cloudbuilder:latest
  dir: /workspace/terraform/
  args:
  - init
  - -input=false
# terraform validate
- id: validate_infrastructure
  name: gcr.ip/$PROJECT_ID/terraform-cloudbuilder:latest
  dir: /workspace/terraform/
  args:
  - validate
# terraform plan -input=false -out=tfplan
- id: plan_infrastructure
  name: gcr.ip/$PROJECT_ID/terraform-cloudbuilder:latest
  dir: /workspace/terraform/
  args:
  - plan
  - -input=false
  - -out=tfplan

artifacts:
  objects:
    location: 'gs://tfstate-demoterraform/cloudbuild/plan/$BUILD_ID'
    paths: ['cloudbuild-plan.yaml', 'tfplan']
